#!/bin/sh
export HISTFILE=/dev/null
if [ "$PS1" ]; then
    export TERM=xterm-256color
    export PS1="\[\033[0;36m\]\w \\$\[\033[0m\] "
    alias ls='ls --color=auto'
    alias ll='ls -alFh --color=auto'
    alias rmr='rm -r'
fi
