define(function () {
    var a = true;
    var b = [{
        hash: "#httpshare_guest",
        path: "sd/httpshare",
        level: "",
        requireLogin: false,
        checkSIMStatus: false
    }, {
        hash: "#login", 
        path: "login", 
        level: "1", 
        requireLogin: false, 
        checkSIMStatus: false
    }, {
        hash: "#home",
        path: "home",
        level: "1",
        requireLogin: a,
        checkSIMStatus: true
    }, {
        hash: "#status",
        path: "status/device_info",
        level: "1",
        requireLogin: a,
        checkSIMStatus: false
    }, {
        hash: "#sms",
        path: "sms/smslist",
        level: "1",
        requireLogin: a,
        checkSIMStatus: false
    }, {
        hash: "#setting",
        path: "adm/quick_setting",
        level: "1",
        requireLogin: a,
        checkSIMStatus: true
    }, {     
        hash: "#welcome", 
        path: "welcome", 
        level: "", 
        requireLogin: false
    }, {
        hash: "#change_password",
        path: "change_password",
        level: "",
        requireLogin: false,
        checkSIMStatus: false
    }, {
        hash: "#smslist",
        path: "sms/smslist",
        level: "2",
        parent: "#sms",
        requireLogin: a,
        checkSIMStatus: false
    },  {
        hash: "#sim_messages",
        path: "sms/sim_messages",
        level: "2",
        parent: "#sms",
        requireLogin: a,
        checkSIMStatus: false
    }, {
        hash: "#sms_setting",
        path: "sms/sms_setting",
        level: "2",
        parent: "#sms",
        requireLogin: a,
        checkSIMStatus: false
    }, {
        hash: "#quick_setting",
        path: "adm/quick_setting",
        level: "2",
        parent: "#setting",
        requireLogin: a,
        checkSIMStatus: true
    }, {
        hash: "#net_setting",
        path: "network/dial_setting",
        level: "2",
        parent: "#setting",
        requireLogin: a,
        checkSIMStatus: true
    }, {
        hash: "#wifi",
        path: "wifi/wifi_basic",
        level: "2",
        parent: "#setting",
        requireLogin: a,
        checkSIMStatus: false
    }, {
        hash: "#device_setting",
        path: "adm/password",
        level: "2",
        parent: "#setting",
        requireLogin: a,
        checkSIMStatus: false
    }, {
        hash: "#firewall",
        path: "firewall/port_filter",
        level: "2",
        parent: "#setting",
        requireLogin: a,
        checkSIMStatus: false
    }, {
        hash: "#router_setting",
        path: "adm/lan",
        level: "2",
        parent: "#setting",
        requireLogin: a,
        checkSIMStatus: false
    }, {
        hash: "#device_info",
        path: "status/device_info",
        level: "2",
        parent: "#status",
        requireLogin: a,
        checkSIMStatus: false
    }, {
        hash: "#traffic_statistics",
        path: "status/traffic_statistics",
        level: "2",
        parent: "#status",
        requireLogin: a,
        checkSIMStatus: false
    }, {
        hash: "#traffic_alert",
        path: "status/traffic_alert",
        level: "2",
        parent: "#status",
        requireLogin: a,
        checkSIMStatus: false
    }, {
        hash: "#change",
        path: "adm/changesim",
        level: "2",
        parent: "#setting",
        requireLogin: a,
        checkSIMStatus: false
    }, {
        hash: "#dial_setting",
        path: "network/dial_setting",
        level: "3",
        parent: "#net_setting",
        requireLogin: a,
        checkSIMStatus: true
    }, {
        hash: "#net_select",
        path: "network/net_select",
        level: "3",
        parent: "#net_setting",
        requireLogin: a,
        checkSIMStatus: true
    }, {
        hash: "#apn_setting",
        path: "network/apn_setting",
        level: "3",
        parent: "#net_setting",
        requireLogin: a,
        checkSIMStatus: true
    }, {
        hash: "#wifi_basic",
        path: "wifi/wifi_basic",
        level: "3",
        parent: "#wifi",
        requireLogin: a,
        checkSIMStatus: false
    }, {
        hash: "#sleep_mode",
        path: "wifi/sleep_mode",
        level: "3",
        parent: "#wifi",
        requireLogin: a,
        checkSIMStatus: false
    }, {
        hash: "#wifi_advance",
        path: "wifi/wifi_advance",
        level: "3",
        parent: "#wifi",
        requireLogin: a,
        checkSIMStatus: false
    }, {
        hash: "#wps",
        path: "wifi/wps",
        level: "3",
        parent: "#wifi",
        requireLogin: a,
        checkSIMStatus: false
    }, {
        hash: "#black_list",
        path: "wifi/mac_filter",
        level: "3",
        parent: "#wifi",
        requireLogin: a,
        checkSIMStatus: false
    }, {
        hash: "#password_management",
        path: "adm/password",
        level: "3",
        parent: "#device_setting",
        requireLogin: a,
        checkSIMStatus: false
    }, {
        hash: "#pin_management",
        path: "adm/pin",
        level: "3",
        parent: "#device_setting",
        requireLogin: a,
        checkSIMStatus: true
    }, {
        hash: "#restore",
        path: "adm/restore",
        level: "3",
        parent: "#device_setting",
        requireLogin: a,
        checkSIMStatus: false
    }, {
        hash: "#restart",
        path: "adm/restart",
        level: "3",
        parent: "#device_setting",
        requireLogin: a,
        checkSIMStatus: false
    }, {
        hash: "#port_filter",
        path: "firewall/port_filter",
        level: "3",
        parent: "#firewall",
        requireLogin: a,
        checkSIMStatus: false
    }, {
        hash: "#port_map",
        path: "firewall/port_map",
        level: "3",
        parent: "#firewall",
        requireLogin: a,
        checkSIMStatus: false
    }, {
        hash: "#upnp",
        path: "firewall/upnp_setting",
        level: "3",
        parent: "#firewall",
        requireLogin: a,
        checkSIMStatus: false
    }, {
        hash: "#dmz",
        path: "firewall/dmz_setting",
        level: "3",
        parent: "#firewall",
        requireLogin: a,
        checkSIMStatus: false
    }, {
        hash: "#ota_update",
        path: "update/ota_update",
        level: "3",
        parent: "#device_setting",
        requireLogin: a,
        checkSIMStatus: false
    }, {
        hash: "#changesim",
        path: "adm/changesim",
        level: "3",
        parent: "#change",
        requireLogin: a,
        checkSIMStatus: false
    }, {
        hash: "#unclock_sim",
        path: "adm/unclock_sim",
        level: "3",
        parent: "#change",
        requireLogin: a,
        checkSIMStatus: false
    }];
    return b
});